### ISSUE TITLE
Update colors on home page to be more accessible

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#1]
As a vision impaired site visitor I want the color contrasts in the header on the homepage to be accessible so that I can easily view the page. 

Acceptance Criteria: 
- New image (background, or logo) is added to replace the current color scheme. Image will be provided by @dtoakley and will be the same dimensions as the current image.  
- Homepage still look good on desktop and mobile.

**Comment by dtoakley** [comment]
Turns our we just need to update the logo image. Here is the new image - it looks the same, but it's subtly better and passes accessibility tests:  

![earth-day-live-wordmark](https://user-images.githubusercontent.com/2144730/77784067-45340680-7030-11ea-83ba-0a00a6eb4d5f.png)

**Comment by EvanHahn** [comment]
Addressed in 79f28144e4769a590981a5caeca84eda7797bca0.
