### ISSUE TITLE
Localize Earth Day Live website

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#18]
As a non-English speaker I want to be able to experience the website in other languages so that I can understand things! 

A/C:
- Localize the entire website so the it can be viewed in other languages. 
- As part of this, please make the homepage available in Spanish to begin with. 
- If there is no translation, it should default to English.
- Please provide a recommendation for how to handle this in the URL (e.g. earthdaylive2020.org/es/, or earthdaylive2020.org?lang=es or es.earthdaylive2020.org)

Notes: 
- Spanish translation of home page is here: https://docs.google.com/document/d/1ynQi-vuqfKpkwp1oVeG1gMgwqVcmZ1E9AnZuNL_IcPk/edit?ts=5e7e0c76
- The get-involved page doesn't need to be localized in this ticket. 
- See an example of this being done here: https://github.com/fightforthefuture/fftf-starter-template

**Comment by jlevers** [comment]
I created a Google sheet [here](https://docs.google.com/spreadsheets/d/1Xm9gR9vzZ5Kc0dhogBirhZvWkqLbu_SiSAsMLwkWUWc/edit) to coordinate translations. Please use the "EDL website" tab for website translations.

**Comment by jlevers** [comment]
To QA this:
* Check out the `i18n` branch and run `npm i`
* Check that `/` and `/get-involved` are both loading in English
* Visit `/es` and `/es/get-involved`, and check that `/es` is in Spanish and `/es/get-involved` defaults to English (since we don't have translations for the Get Involved page)
