### ISSUE TITLE
Add Google Analytics tracking to the website

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#2]
As a campaign team we want Google Analytics tracking set up so that we can understand how the site is performing. 

A/C:
- Decide whether to do GA via Google Tag Manager or not.
- Implement Google Analytics so that we can track page views. 

Out of scope:
- Events for clicks, form submissions, etc. This is only to track page views for now.

**Comment by dtoakley** [comment]
Here is the GA tracking tag:

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-162257314-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-162257314-1');
</script>
`

**Comment by alexperson-tw** [comment]
Here's a link to the Nuxt documentation I used to set up GA for Earth Day Live that currently allows us to track page views:
https://nuxtjs.org/faq/google-analytics/

From what I can tell from the GA dashboard, it seems to be working.

<img width="1790" alt="Screen Shot 2020-04-02 at 9 57 57 AM" src="https://user-images.githubusercontent.com/62622249/78264655-0d620e80-74c9-11ea-9a3b-b1ae288e853c.png">
