### ISSUE TITLE
Scrolling not working on get-involved/index.html

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#23]
Steps to replicate:

1. Go here: https://www.earthdaylive2020.org/get-involved/index.html
2. Click the nav or "I'm raady"
3. Scrolling is broken.

Please fix this! It seems to work on https://www.earthdaylive2020.org/get-involved/ - maybe it's a caching issue?

Update- seems to be working. Card completed?

**Comment by dtoakley** [comment]
This is quite weird and hard to pin down. There seems to be various solutions that I tried but none seemed to work: https://github.com/nuxt/nuxt.js/issues/5800

To fix this for now, I've used Cloudflare to redirect https://www.earthdaylive2020.org/get-involved to https://www.earthdaylive2020.org/get-involved/ so we never hit the /index.html page. 

Moving this to the backlog for now.

**Comment by charlottecooke** [comment]
Hi, I'm not seeing this as broken? 🤔
