### ISSUE TITLE
Set up CI/CD for the Earth Day Live Website

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#3]
As a dev team I want CI/CD set up for the Earth Day Live website so that we can ensure correctness of code and efficiency in software development as a team. 

A/C:
- Set up automated builds with TravisCI
- The build should run the unit/component tests 
- The build should lint the code 
- The build should give a code coverage read out
- Deployment should be blocked if build fails. Warnings don't need to cause a failure - errors should. 
- Deployment can be automated to stage.earthdaylive2020.org.
- Deployment to www.earthdaylive2020.org needs to be human triggered (push button deploy).

**Comment by dfratte-tw** [comment]
Waiting for access to TravisCI dashboard to handle GitHub integration

**Comment by dtoakley** [comment]
We have TravisCI integration set up now: https://travis-ci.com/github/fightforthefuture/earth-day-live

So let's add some basic travis.yml config and get this running :)

**Comment by dfratte-tw** [comment]
Setup of the infrastructure config is done. Deployment to staging needs access information to be setup in .travis.yml. Other stages (linting and testing) are working fine (checkout TravisCI dashboard), though they have a basic configuration which might need tuning/refactoring according to new A/Cs (e.g. new rules for linting).

**Comment by dtoakley** [comment]
I've added all the necessary config and environment variables, and the build & deploy "succeeds" - however the bucket isn't updated. I've submitted a help ticket because there aren't any useful logs at all, and I don't have permission to run the build in debug mode....

Latest build: https://travis-ci.com/github/fightforthefuture/earth-day-live

**Comment by dtoakley** [comment]
Okay - i got this working. It seems the syntax used by the travis CLI to auto-generate the .travis.yml file is either a little out of date, or too modern for the syntax travis uses to parse the file. I updated it to the syntax I used in a previous project and it's working. Closing this off!
