### ISSUE TITLE
Add instructions to get-involved page for installing the javascript widget via Wordpress, Shopify, Squarespace and Wix. 

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#34]
As some who runs a Wordpress, SquareSpace, Shopify or Wix site, I want to have instructions on the get-involved page for installing the javascript widget so that I can join the campaign. 

A/C:
- The following text is added to the WebsiteBanner.vue component, below the "Try it out" button: 
"Here are instructions for installing the widget on your site:"
- Tumble link: https://docs.google.com/document/d/1BvUz4f6hSrOcLhNSIBq4GUTeeA9Cvb6vdis3F0-Tnuo/edit?ts=5e8a4d7b
- Squarespace link: https://docs.google.com/document/d/116ZqH8l68HaolxQQIxIuLwCuo-7EjnrCC_Cu76B3sEA/edit?ts=5e8a5156

**Comment by dtoakley** [comment]
Arne and I added the first two links (Tumblr and Squarespace). We need to add Shopify and Wix before deploying. And also add some tests at some point!

**Comment by arnelaponin** [comment]
I extracted the code Dan wrote into a separate component called WidgetInstructions. I added some tests for the component as well.
