### ISSUE TITLE
Add "Copy URL" share option to SignUpShareComponent

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#43]
As a user who signs up, I want an option to "Copy" the share URL so that I can paste it wherever I want.

A/C:
- An input field is displayed below the other share options that includes the Copy share URL
- A button is to the right of it, and when clicked, copies the URL to the user's clipboard. 

Notes:
- @dtoakley can provide design direction for this.

**Comment by charlottecooke** [comment]
Felt super weird pushing to master directly! 😱  

Here's what it looks like currently, let me know if you think there needs to be any changes 👍 

![image](https://user-images.githubusercontent.com/36961462/79077108-cbba3a80-7cf6-11ea-85ec-b0c0871c9b70.png)
![image](https://user-images.githubusercontent.com/36961462/79077112-d543a280-7cf6-11ea-9312-d8b4539a4e23.png)
