### ISSUE TITLE
Pre-fill Email and  Zip Code for Register to vote form

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#45]
As a user who RSVP'd to the livestream, I want me email and zip code to be pre-filled in the RegisterToVote form so that the process is eaiser. 

A/C:
- After the user successfully submits the SignUpForm, we should append the email and zip code used in the submission to the iFrame URL in the RegisterToVoteForm. 
- It should look like this: https://register.rockthevote.com?partner=38367&email_address=d.lewistoakley+test@gmail.com&home_zip_code=11216

Notes:
- We may need to store this data in a cookie or session storage, and update it each time someone clicks the RSVP form submit button, because I don't think it exists in the response back from Action Network on successful form completion (the 'can_embed_submitted' event)

**Comment by Ram2103** [comment]
I tested this functionality in chrome and safari browser, the details which we have entered in the SingUp form is not reflecting in the RegisterToVote form as expected.

**Comment by jlevers** [comment]
Strange, it was working for me in Firefox -- I'll take a look at it tonight.
