### ISSUE TITLE
Add unit/component tests to home page

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/earth-day-live#9]
As a dev team I want some unit/component tests for the homepage so we can ensure correctness and allow for CI. 

A/C:
- Jest tests are added for the home page 
- Tests should be green 
- Tests should probably cover that the logo, title and subtitle and rendered - maybe more than this - have a think. 

Notes:
- Use your judgement to determine the breadth and depth. I advise you to follow the testing pyramid as much as is reasonable. 

Out of scope:
- Tests that cover the form on the homepage because is an external dependency that is injected into the DOM. Not our responsibility!

**Comment by dfratte-tw** [comment]
A/C update:
Logo -> DONE
Title  -> DONE
